### ISSUE TITLE
cupiditys iReady-Overload GitHub page got deleted  (i think)

### ISSUE THREAD

**Issue by SusyBo1** [HypnoticLOL/cReady#1]
![image](https://user-images.githubusercontent.com/95867977/154072481-8cadfd22-f263-4c76-9233-1a7d32c4e4a5.png)

**Comment by SusyBo1** [comment]
Your page also
![image](https://user-images.githubusercontent.com/95867977/154073986-4aab316f-5fa6-4a31-8f43-69936b423faf.png)

**Comment by SharkiArthur** [comment]
yup it did cupid knows about this already.

**Comment by SusyBo1** [comment]
> yup it did cupid knows about this already.

Do you know why? Also that's sad :(

**Comment by HypnoticLOL** [comment]
yes I do

**Comment by HypnoticLOL** [comment]
![EA4F561A-DD06-484A-9B9C-F18C84CAADA0](https://user-images.githubusercontent.com/96861065/154158464-2ae621be-9e0a-48d5-acd4-a7e2ccd4058a.jpg)

**Comment by HypnoticLOL** [comment]
u can still use this tho https://chrome.google.com/webstore/detail/iready-overload/ddpalhmjafimblgfecimmdeafainoapp

**Comment by SusyBo1** [comment]
@HypnoticLOL did i-Ready patch the latest bookmark.txt if not do you have the latest bookmark.txt? (p.s the latest is ver. 0.1.11)

**Comment by HypnoticLOL** [comment]
they didnt patch, and no cupid blocked me on discord so I dont have shit

**Comment by SharkiArthur** [comment]
Good

**Comment by HypnoticLOL** [comment]
> Your page also ![image](https://user-images.githubusercontent.com/95867977/154073986-4aab316f-5fa6-4a31-8f43-69936b423faf.png)

yea I privated it cuz it would get u blocked by just using it

**Comment by SharkiArthur** [comment]
Trash

**Comment by HypnoticLOL** [comment]
just like u
![Screenshot 2022-02-16 5 41 49 PM](https://user-images.githubusercontent.com/96861065/154376118-57a93a6f-8ff7-4524-b276-b1f77e479a60.png)

**Comment by SharkiArthur** [comment]
Damm really bought u nitro and u say this and Cupid told me to block u

**Comment by SharkiArthur** [comment]
![BRUH](https://user-images.githubusercontent.com/91421571/154379606-578a0bec-951f-43ac-9282-5dbbf3f01ae7.png)
GO CHECK UR DISCORD

**Comment by SharkiArthur** [comment]
This will be closed due to cupids account prob not being unbanned please use this for now.
https://github.com/SharkiArthur/cupiditysmenurevised

Thanks

**Comment by SharkiArthur** [comment]
Hypnotic friend my snap SharkiArthur
